### ISSUE TITLE
Adding trigger button functionality

### ISSUE THREAD

**Issue by raunak51299** [manankohlii/spacex-launch-data#19] opened 2021-06-06 17:21 UTC
I would like add the functionality of searching the mission when the Enter key is pressed.
Please assign me this issue under LGM SOC.

**Comment by manankohlii** [comment] 2021-06-07 03:33
@raunak51299 assigned.

**Comment by harshita9621** [comment] 2021-06-09 10:29
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by manankohlii** [comment] 2021-06-09 17:59
@harshita9621 if the issue is not resolved in a few more days by the assignee, you may work on it.

**Comment by harshita9621** [comment] 2021-06-09 18:11
Okay @manankohlii

**Comment by manankohlii** [comment] 2021-06-09 20:10
I am closing this issue as it has been resolved.

**Closed by manankohlii** 2021-06-09 20:10 UTC
